title: "Umberto Platini"
author: "Umberto Platini"
description: "Università Bocconi" #color: #f45;\">&lt;3</b>"
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

# Layout

show_excerpts: false #true        # show article excerpts on the home page
show_frame: false           # adds a gray frame to the site
show_sidebar: false        # show a sidebar instead of the usual header
minimal: false             # use a dark header

# Menu

navigation:                # accepts {file, title, url, icon, sidebaricon}
  - {file: "index.md", title: "Home"}
  - {title: "Research", file: "research.md"}
  - {title: "CV", file: "/Curriculum Vitae.pdf}
  - {title: "Blog", file: "blog.md"}

external:                  # shows a footer with social links - for available icons see fontawesome.com/icons
  - {title: Mail, icon: envelope, url: "mailto:umberto.platini@unibocconi.it"}
  - {title: Github, icon: github, url: "https://github.com/uplatini"}
  - {title: Twitter, icon: twitter, url: "https://twitter.com/umbertoplatini"}

comments:
#  disqus_shortname: ""    # see https://disqus.com/
#  isso_domain: ""         # see https://posativ.org/isso/

plugins:
 - jekyll-feed
